// This file is @generated by prost-build.
/// 采集请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CollectRequest {
    /// 任务ID（用于追踪）
    #[prost(string, tag = "1")]
    pub task_id: ::prost::alloc::string::String,
    /// bpftrace脚本路径
    #[prost(string, tag = "2")]
    pub script_path: ::prost::alloc::string::String,
    /// 脚本内容（可选，优先于script_path）
    #[prost(string, tag = "3")]
    pub script_content: ::prost::alloc::string::String,
    /// 采集时长
    #[prost(uint64, tag = "4")]
    pub duration_secs: u64,
    /// 目标进程PID（可选）
    #[prost(uint32, optional, tag = "5")]
    pub scope_pid: ::core::option::Option<u32>,
    /// 目标cgroup（可选）
    #[prost(string, optional, tag = "6")]
    pub cgroup_id: ::core::option::Option<::prost::alloc::string::String>,
    /// 证据类型
    #[prost(string, tag = "7")]
    pub evidence_type: ::prost::alloc::string::String,
    /// 额外参数
    #[prost(map = "string, string", tag = "8")]
    pub params: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
/// 采集响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CollectResponse {
    /// 采集ID
    #[prost(string, tag = "1")]
    pub collection_id: ::prost::alloc::string::String,
    /// 原始输出（JSON Lines）
    #[prost(bytes = "vec", tag = "2")]
    pub raw_output: ::prost::alloc::vec::Vec<u8>,
    /// 实际耗时
    #[prost(uint64, tag = "3")]
    pub duration_ms: u64,
    /// 状态: success, timeout, error, cancelled
    #[prost(string, tag = "4")]
    pub status: ::prost::alloc::string::String,
    /// 错误信息
    #[prost(string, optional, tag = "5")]
    pub error_msg: ::core::option::Option<::prost::alloc::string::String>,
    /// 采集到的事件数
    #[prost(uint32, tag = "6")]
    pub event_count: u32,
    /// 采集到的字节数
    #[prost(uint64, tag = "7")]
    pub bytes_collected: u64,
}
/// /proc读取请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReadProcRequest {
    /// 任务ID
    #[prost(string, tag = "1")]
    pub task_id: ::prost::alloc::string::String,
    /// /proc/下的路径，如 "1234/maps"
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
    /// 目标PID
    #[prost(uint32, optional, tag = "3")]
    pub pid: ::core::option::Option<u32>,
    /// 是否跟随符号链接
    #[prost(bool, tag = "4")]
    pub follow_symlink: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReadProcResponse {
    /// 文件内容
    #[prost(bytes = "vec", tag = "1")]
    pub content: ::prost::alloc::vec::Vec<u8>,
    /// 文件是否存在
    #[prost(bool, tag = "2")]
    pub exists: bool,
    /// 错误信息
    #[prost(string, optional, tag = "3")]
    pub error_msg: ::core::option::Option<::prost::alloc::string::String>,
}
/// 取消采集请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CancelRequest {
    /// 要取消的采集ID
    #[prost(string, tag = "1")]
    pub collection_id: ::prost::alloc::string::String,
    /// 取消原因
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CancelResponse {
    /// 是否成功取消
    #[prost(bool, tag = "1")]
    pub success: bool,
    /// 取消后的状态
    #[prost(string, tag = "2")]
    pub status: ::prost::alloc::string::String,
}
/// 健康检查请求
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct HealthRequest {
    /// 是否包含统计信息
    #[prost(bool, tag = "1")]
    pub include_stats: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HealthResponse {
    /// 是否健康
    #[prost(bool, tag = "1")]
    pub healthy: bool,
    /// 版本号
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
    /// 当前活跃采集数
    #[prost(uint32, tag = "3")]
    pub active_collections: u32,
    /// 总采集次数
    #[prost(uint64, tag = "4")]
    pub total_collections: u64,
    /// 运行时长（秒）
    #[prost(uint64, tag = "5")]
    pub uptime_secs: u64,
    /// 监听地址
    #[prost(string, tag = "6")]
    pub socket_path: ::prost::alloc::string::String,
    /// 当前拥有的capabilities
    #[prost(string, repeated, tag = "7")]
    pub capabilities: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// 采集器统计信息
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CollectorStats {
    #[prost(uint64, tag = "1")]
    pub total_requests: u64,
    #[prost(uint64, tag = "2")]
    pub success_count: u64,
    #[prost(uint64, tag = "3")]
    pub error_count: u64,
    #[prost(uint64, tag = "4")]
    pub timeout_count: u64,
    /// 按证据类型统计
    #[prost(map = "string, uint64", tag = "5")]
    pub evidence_type_counts: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        u64,
    >,
    #[prost(uint64, tag = "6")]
    pub bytes_collected_total: u64,
}
/// 权限检查请求
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PermissionCheckRequest {
    /// 要检查的UID
    #[prost(uint32, tag = "1")]
    pub uid: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PermissionCheckResponse {
    /// 是否允许访问
    #[prost(bool, tag = "1")]
    pub allowed: bool,
    /// 授予的权限
    #[prost(string, repeated, tag = "2")]
    pub granted_permissions: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// 提示信息
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
}
/// Generated client implementations.
pub mod collector_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// 服务定义
    #[derive(Debug, Clone)]
    pub struct CollectorClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl CollectorClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> CollectorClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> CollectorClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            CollectorClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// 执行bpftrace采集
        pub async fn collect_bpftrace(
            &mut self,
            request: impl tonic::IntoRequest<super::CollectRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CollectResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/nuts.collector.Collector/CollectBpftrace",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("nuts.collector.Collector", "CollectBpftrace"));
            self.inner.unary(req, path, codec).await
        }
        /// 读取/proc文件
        pub async fn read_proc(
            &mut self,
            request: impl tonic::IntoRequest<super::ReadProcRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ReadProcResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/nuts.collector.Collector/ReadProc",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("nuts.collector.Collector", "ReadProc"));
            self.inner.unary(req, path, codec).await
        }
        /// 取消正在进行的采集
        pub async fn cancel_collection(
            &mut self,
            request: impl tonic::IntoRequest<super::CancelRequest>,
        ) -> std::result::Result<tonic::Response<super::CancelResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/nuts.collector.Collector/CancelCollection",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("nuts.collector.Collector", "CancelCollection"));
            self.inner.unary(req, path, codec).await
        }
        /// 健康检查
        pub async fn health(
            &mut self,
            request: impl tonic::IntoRequest<super::HealthRequest>,
        ) -> std::result::Result<tonic::Response<super::HealthResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/nuts.collector.Collector/Health",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("nuts.collector.Collector", "Health"));
            self.inner.unary(req, path, codec).await
        }
        /// 检查权限
        pub async fn check_permission(
            &mut self,
            request: impl tonic::IntoRequest<super::PermissionCheckRequest>,
        ) -> std::result::Result<
            tonic::Response<super::PermissionCheckResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/nuts.collector.Collector/CheckPermission",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("nuts.collector.Collector", "CheckPermission"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod collector_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with CollectorServer.
    #[async_trait]
    pub trait Collector: std::marker::Send + std::marker::Sync + 'static {
        /// 执行bpftrace采集
        async fn collect_bpftrace(
            &self,
            request: tonic::Request<super::CollectRequest>,
        ) -> std::result::Result<tonic::Response<super::CollectResponse>, tonic::Status>;
        /// 读取/proc文件
        async fn read_proc(
            &self,
            request: tonic::Request<super::ReadProcRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ReadProcResponse>,
            tonic::Status,
        >;
        /// 取消正在进行的采集
        async fn cancel_collection(
            &self,
            request: tonic::Request<super::CancelRequest>,
        ) -> std::result::Result<tonic::Response<super::CancelResponse>, tonic::Status>;
        /// 健康检查
        async fn health(
            &self,
            request: tonic::Request<super::HealthRequest>,
        ) -> std::result::Result<tonic::Response<super::HealthResponse>, tonic::Status>;
        /// 检查权限
        async fn check_permission(
            &self,
            request: tonic::Request<super::PermissionCheckRequest>,
        ) -> std::result::Result<
            tonic::Response<super::PermissionCheckResponse>,
            tonic::Status,
        >;
    }
    /// 服务定义
    #[derive(Debug)]
    pub struct CollectorServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> CollectorServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for CollectorServer<T>
    where
        T: Collector,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/nuts.collector.Collector/CollectBpftrace" => {
                    #[allow(non_camel_case_types)]
                    struct CollectBpftraceSvc<T: Collector>(pub Arc<T>);
                    impl<T: Collector> tonic::server::UnaryService<super::CollectRequest>
                    for CollectBpftraceSvc<T> {
                        type Response = super::CollectResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CollectRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Collector>::collect_bpftrace(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CollectBpftraceSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/nuts.collector.Collector/ReadProc" => {
                    #[allow(non_camel_case_types)]
                    struct ReadProcSvc<T: Collector>(pub Arc<T>);
                    impl<
                        T: Collector,
                    > tonic::server::UnaryService<super::ReadProcRequest>
                    for ReadProcSvc<T> {
                        type Response = super::ReadProcResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ReadProcRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Collector>::read_proc(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ReadProcSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/nuts.collector.Collector/CancelCollection" => {
                    #[allow(non_camel_case_types)]
                    struct CancelCollectionSvc<T: Collector>(pub Arc<T>);
                    impl<T: Collector> tonic::server::UnaryService<super::CancelRequest>
                    for CancelCollectionSvc<T> {
                        type Response = super::CancelResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CancelRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Collector>::cancel_collection(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CancelCollectionSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/nuts.collector.Collector/Health" => {
                    #[allow(non_camel_case_types)]
                    struct HealthSvc<T: Collector>(pub Arc<T>);
                    impl<T: Collector> tonic::server::UnaryService<super::HealthRequest>
                    for HealthSvc<T> {
                        type Response = super::HealthResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::HealthRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Collector>::health(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = HealthSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/nuts.collector.Collector/CheckPermission" => {
                    #[allow(non_camel_case_types)]
                    struct CheckPermissionSvc<T: Collector>(pub Arc<T>);
                    impl<
                        T: Collector,
                    > tonic::server::UnaryService<super::PermissionCheckRequest>
                    for CheckPermissionSvc<T> {
                        type Response = super::PermissionCheckResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::PermissionCheckRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Collector>::check_permission(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CheckPermissionSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for CollectorServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "nuts.collector.Collector";
    impl<T> tonic::server::NamedService for CollectorServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
